server {
  listen 80;
  server_name _;
  root /usr/share/nginx/html;
  index index.html;

  location /assets/ { try_files $uri =404; expires 7d; add_header Cache-Control "public, immutable"; }
  location /demos/vanilla/ { try_files $uri $uri/ /demos/vanilla/index.html; }
  location /demos/vue2/ { try_files $uri $uri/ /demos/vue2/index.html; }
  location /demos/vue3/ { try_files $uri $uri/ /demos/vue3/index.html; }
  location / { try_files $uri $uri.html $uri/ /404.html; }
}
